In order to successfully complete this assignment you must do the required reading, watch the provided videos and complete all instructions.  The embedded Google form must be entirely filled out and submitted on or before **11:59pm on Wednesday October 23**.  Students must come to class the next day prepared to discuss the material covered in this assignment. answer

# Pre-Class Assignment: Diagonalization and Powers

# Goals for today's pre-class assignment 

</p>



1. [Eigenvalues and eigenvectors review](#Eigenvalues_and_eigenvectors_review)
1. [Diagonalizable Matrix](#Diagonalizable_Matrix)
1. [Assignment wrap-up](#Assignment_wrap-up)

In [1]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing()

----
<a name="Eigenvalues_and_eigenvectors_review"></a>
# 1. Eigenvalues and eigenvectors review

**Definition**: A non-zero vector $x$ in $R^n$ is called an *eigenvector* of a $n\times n$ matrix $A$ if $Ax$ is a scalar multiple of $x$. If $Ax = \lambda x$, then $\lambda$ is called the *eigenvalue* of $A$ corresponding to $x$.

### Steps for Finding the eigenvalues and eigenvectors

We want to find $\lambda$ and non-zero vector $x$ such that $Ax=\lambda x$ for a $n\times n$ matrix. 
1. We introduce an identity matrix $I$ of $n\times n$. Then the equation becomes
$$Ax = \lambda I x$$
$$Ax-\lambda I x = 0$$
$$(A-\lambda I)x = 0$$
2. This suggests that we want to find $\lambda$ such that $(A-\lambda I)x=0$ has non-trivial solution. 
It is equivalent to that the matrix $A-\lambda I$ is singular, i.e., has a determinant of $0$.
$$|A-\lambda I|=0$$
3. The determinant is polynomial in $\lambda$ (called the characteristic polynomial of $A$) with degree $n$. We solve this equation (called the characteristic equation) for all possible $\lambda$ (eigenvalues).
4. After find the eigenvalues, substitute them back into 
$$(A-\lambda I)x=0$$
and find the eigenvectors $x$. 


Lets consider an example. Lets calculate eigenvalues for the folling matrix: 

$$ A=\begin{bmatrix} 0 & 0 & -2 \\ 1 & 2 & 1 \\ 1 & 0 & 3 \end{bmatrix}$$

&#9989; <font color=red>**Do This:**</font>  First, lets do use the built in funciton ```eigenvals``` function in ```sympy``` to calculate the eigenvalues

In [3]:
A = sym.Matrix([[0,0,-2],[1,2,1],[1,0,3]])
A.eigenvals()

That should work but it dosn't show us what is going on.  Looking at the above recipe, lets solve the problem symbollically using sympy. First lets create a matrix $B$ such that:

$$B = A-\lambda I$$

In [5]:
#Most sympy requires defeing the variables as "symbols"
#Once we do this we can use the variables in place of numbers
lam = sym.symbols('lambda')

A = sym.Matrix([[0, 0 ,-2], [1, 2, 1], [1, 0, 3]])
I = sym.eye(3)

B = A - lam*I

B

⎡-λ    0       -2  ⎤
⎢                  ⎥
⎢1   -λ + 2    1   ⎥
⎢                  ⎥
⎣1     0     -λ + 3⎦

Now, per step 2 the determinate of $B$ must be zero. Note that sympy calculates the determinate symbollically as follows:

In [6]:
B.det()

&#9989; <font color=red>**Do This:**</font>  Using the ```sympy.solve``` function on the determinate of $B$ solve for ```lam``` ($\lambda$).

In [7]:
# Put your code to solve for det(B) = 0 here
sym.solve(B.det())

Verify that the solution to the last question produces the same eigenvalues as above. 

Now that we know the eigenvalues we can substitue them back into the equation to find the eigenvectors.  

&#9989; <font color=red>**Do This:**</font>  First, lets use the ```eigenvects```  function in ```sympy```find three linear independent eigenvectors for the matrix $A$?

In [8]:
# Put your answer to the above question here
B.eigenvects()

⎡⎛           ⎡⎡-2⎤⎤⎞  ⎛           ⎡⎡0⎤  ⎡-1⎤⎤⎞⎤
⎢⎜           ⎢⎢  ⎥⎥⎟  ⎜           ⎢⎢ ⎥  ⎢  ⎥⎥⎟⎥
⎢⎜-λ + 1, 1, ⎢⎢1 ⎥⎥⎟, ⎜-λ + 2, 2, ⎢⎢1⎥, ⎢0 ⎥⎥⎟⎥
⎢⎜           ⎢⎢  ⎥⎥⎟  ⎜           ⎢⎢ ⎥  ⎢  ⎥⎥⎟⎥
⎣⎝           ⎣⎣1 ⎦⎦⎠  ⎝           ⎣⎣0⎦  ⎣1 ⎦⎦⎠⎦

Next break down these steps and solve this symbollically using sympy. First lets make a vector of our eigenvalues (from above):

In [9]:
eig = [1,2]

Now (per step 4 above) we need to solve the equation $(A-\lambda I)x=0$. One way to do this in numpy is as follows:

In [10]:
x1,x2,x3 = sym.symbols(['x_1','x_2','x_3'])

x = sym.Matrix([[x1],[x2],[x3]])
x

⎡x₁⎤
⎢  ⎥
⎢x₂⎥
⎢  ⎥
⎣x₃⎦

In [11]:
for e in eig:
    vec = sym.solve((A - e*I)*x,x)
    print(vec)

{x_2: x_3, x_1: -2*x_3}
{x_1: -x_3}


&#9989; <font color=red>**QUESTION:**</font>  Compare this answer to the eigenvectors we calculated above. Does this answer make sense?  What does the syntax tell us? 

eigenvects gives us an example of a vector, while sym solve gives us a general form of the vector

&#9989; <font color=red>**DO THIS:**</font> Find the eigenvalues and eigenvectors of the following matrix:
$$ A2=\begin{bmatrix} 2 & 1 \\ 0 & 2 \end{bmatrix}$$

&#9989; <font color=red>**QUESTION:**</font>  What are the eigenvalues for the matrix $A2$?

In [14]:
A2 = sym.Matrix([[2,1],[0,2]])
A2.eigenvals()

&#9989; <font color=red>**QUESTION 6:**</font>  What are the eigenvectors for the matrix $A2$?

In [13]:
A2.eigenvects()

⎡⎛      ⎡⎡1⎤⎤⎞⎤
⎢⎜2, 2, ⎢⎢ ⎥⎥⎟⎥
⎣⎝      ⎣⎣0⎦⎦⎠⎦

----
<a name="Diagonalizable_Matrix"></a>
# 2. Diagonalizable Matrix

In class we will be using matrix diagonalization to solve some problems.  


&#9989; <font color=red>**DO THIS:**</font>  Review Section 5.3 of the text book (Pages 316-327)

Matrix $A$ is diagonalizable if there exists a diagonal matrix $D$ that is similar similar to $A$:

$$ D = C^{-1}AC$$

If Matrix $A$ has linearly independent eigenvectors ($v_1, \ldots v_n$) then $A$ is Diagonalizable with the following solution:

$$C = \left[ v_1^T, \ldots, v_n^T \right]$$

In other words $C$ each column of $C$ is a linearly independent eigenvector of $A$.

$$ D = 
\left[
\begin{matrix}
    \lambda_1  & 0   \\
    0   & \ddots & 0  \\
    0   & 0 & \lambda_n 
\end{matrix}
\right] 
$$

In other words $D$ consists of the corresponding eigenvalues situation.

In [15]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing(use_unicode=True)

&#9989; <font color=red>**DO THIS:**</font> Using ```numpy```, Diagonalize (i.e. calculate  C and D) the following matrix:

In [16]:
A = np.matrix([[5, -2, 2], [4, -3, 4], [4,-6,7]])
sym.Matrix(A)

⎡5  -2  2⎤
⎢        ⎥
⎢4  -3  4⎥
⎢        ⎥
⎣4  -6  7⎦

In [32]:
# Put your answer here
values = np.linalg.eig(A)[0]
vectors = np.linalg.eig(A)[1]
print(vectors)
D = np.matrix([[values[0],0,0],[0,values[1],0],[0,0,values[2]]])
print(D)
C = vectors
print(C)

[[-5.77350269e-01  6.40987562e-17 -7.07106781e-01]
 [-5.77350269e-01  7.07106781e-01  2.77555756e-16]
 [-5.77350269e-01  7.07106781e-01  7.07106781e-01]]
[[5. 0. 0.]
 [0. 1. 0.]
 [0. 0. 3.]]
[[-5.77350269e-01  6.40987562e-17 -7.07106781e-01]
 [-5.77350269e-01  7.07106781e-01  2.77555756e-16]
 [-5.77350269e-01  7.07106781e-01  7.07106781e-01]]


&#9989; <font color=red>**DO THIS:**</font> Verify that $A$ is in fact Diagonalizable by calculating $D2 = C^{-1}AC$ and comparing it to your original $D$ using ```np.allclose```.

In [33]:
#Put your verificaiton code here.
D2 = np.linalg.inv(C) * A * C
print(D2)

[[ 5.00000000e+00  8.88178420e-16 -1.77635684e-15]
 [-3.44169138e-15  1.00000000e+00  1.11022302e-15]
 [ 2.22044605e-15 -1.77635684e-15  3.00000000e+00]]


In [34]:
np.allclose(D,D2)

True

## Diagonalization of Symmetric Matrices

One special case is Symmetric Matrices.  It can be shown (See book) that symmetric Matrices are Diagonalizable and the resulting eigenvectors are not only linearly independent but also orthogonal.    Since this is true, the equation changes to: 


$$ D = C^{T}AC$$

&#9989; <font color=red>**QUESTION:**</font> Why do we care if $C$ is orthogonal?  What advantages does the above equation give us?

If C is orthogonal, then C^-1 is C^T

$$ A = CDC^{-1} $$
$$ A^T = (CDC^{-1})^T = C^{-1^T}DC^T = CDC^T $$

This equation is faster to compute because transpose only requires some shuffling while calculating the inverse takes O(n^3)

----

<a name="Assignment_wrap-up"></a>
# 3. Assignment wrap-up

Please fill out the form that appears when you run the code below.  **You must completely fill this out in order to receive credit for the assignment!**

[Direct Link to Google Form](https://cmse.msu.edu/cmse314-pc-survey)


If you have trouble with the embedded form, please make sure you log on with your MSU google account at [googleapps.msu.edu](https://googleapps.msu.edu) and then click on the direct link above.

&#9989; <font color=red>**Assignment-Specific QUESTION:**</font> There is no Assignment specific question for this notebook. You can just say "none".

Put your answer to the above question here

&#9989; <font color=red>**QUESTION:**</font>  Summarize what you did in this assignment.

Put your answer to the above question here

&#9989; <font color=red>**QUESTION:**</font>  What questions do you have, if any, about any of the topics discussed in this assignment after working through the jupyter notebook?

Put your answer to the above question here

&#9989; <font color=red>**QUESTION:**</font>  How well do you feel this assignment helped you to achieve a better understanding of the above mentioned topic(s)?

Put your answer to the above question here

&#9989; <font color=red>**QUESTION:**</font> What was the **most** challenging part of this assignment for you? 

Put your answer to the above question here

&#9989; <font color=red>**QUESTION:**</font> What was the **least** challenging part of this assignment for you? 

Put your answer to the above question here

&#9989; <font color=red>**QUESTION:**</font>  What kind of additional questions or support, if any, do you feel you need to have a better understanding of the content in this assignment?

Put your answer to the above question here

&#9989; <font color=red>**QUESTION:**</font>  Do you have any further questions or comments about this material, or anything else that's going on in class?

Put your answer to the above question here

&#9989; <font color=red>**QUESTION:**</font> Approximately how long did this pre-class assignment take?

Put your answer to the above question here

In [5]:
from IPython.display import HTML
HTML(
"""
<iframe 
	src="https://cmse.msu.edu/cmse314-pc-survey" 
	width="100%" 
	height="1000px" 
	frameborder="0" 
	marginheight="0" 
	marginwidth="0">
	Loading...
</iframe>
"""
)

---------
### Congratulations, we're done!

To get credit for this assignment you must fill out and submit the above Google From on or before the assignment due date.

### Course Resources:

- [Syllabus](https://docs.google.com/document/d/e/2PACX-1vRAFflQFXulzSMwWcyr_SEd6piEzHLWTjGkwx49D6H6FZxQGWEHrKMDiIaV3Pu6adAQ-wjlg3IXptjM/pub)
- [Preliminary Schedule](https://docs.google.com/spreadsheets/d/e/2PACX-1vS5UoXTmHDnF99kTHOiHIWuOBG7iqts-8EsbpoJHayRTB7F8eI4SfMR0MVp7dt0RQrMkNTVW6M1x-wY/pubhtml)
- [Course D2L Page](https://d2l.msu.edu/d2l/home/832635)

&#169; Copyright 2019,  Michigan State University Board of Trustees